# Default values for cilium-cni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cilium:
  namespaceOverride: "choreo-dp"
  aksbyocni:
    enabled: true
  encryption:
    enabled: true
    type: wireguard
  envoyConfig:
    enabled: true
  envoy:
    enabled: false
  cluster:
    name: choreo-dp-cluster
  priorityClassName: system-node-critical
  hubble:
    enabled: false
  ipam:
    operator:
      clusterPoolIPv4PodCIDRList: ["10.100.0.0/16"]
  operator:
    rollOutPods: true
    unmanagedPodWatcher:
      restart: true
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    podDisruptionBudget:
      enabled: true
      minAvailable: "50%"
      maxUnavailable: ""
    priorityClassName: system-cluster-critical
  startupProbe:
    failureThreshold: 600
  policyEnforcementMode: default
  routingMode: tunnel
  kubeProxyReplacement: false
  rollOutCiliumPods: true
  extraConfig:
    http-retry-count: "0"
